# -*- coding: utf-8 -*-
"""Auto Timeline.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L9uzP0BOafZVVdEOhOyF4ZPjY1q1bvl9
"""

#!pip install wikipedia
#!pip install spacy
#!pip install pandas
#!pip install nltk

import wikipedia as w  # try https://en.wikipedia.org/wiki/Portal:Current_events
import nltk
import spacy
from spacy import displacy
import pandas as pd
import numpy as np
from pprint import pprint
from flask import Flask, request, render_template
#from spacy import en_core_web_sm
app = Flask(__name__)
#GET from the user

@app.route('/')
def my_form():
    return render_template('my-form.html')
#phrase=input(" Enter your search")
@app.route('/', methods=['POST'])
def my_form_post():
    text = request.form['text']
#post to the user
    phrase=text
    result=w.search(phrase,results=10,suggestion=False) #suggestion can be true or False
    for i in result:
        return i
    
   # for c, value in enumerate(result, 1):
       # return(c, value)
'''
#get from the user
ch=int(input("Enter the index no. to get the summary"))
title1=result[ch-1]
s=w.page(title=title1,pageid=None,auto_suggest=True,redirect=True,preload=False)

#post
print(s)
s1=s.summary
print(s1)
#wikipedia.summary(query, sentences=1, chars=1, auto_suggest=True, redirect=True)
#ss=w.summary(title1, sentences=1, chars=1, auto_suggest=True, redirect=True)
#print(ss)

nlp = spacy.load('en_core_web_sm')
doc = nlp(s1)
pprint([(X.text, X.label_) for X in doc.ents])
labels = [x.label_ for x in doc.ents]

displacy.serve(nlp(str(s1)), style='ent')
#display(HTML(html))
'''
if __name__=="__main__":
    app.run()


